config/routes.rb
Projekt::Application.routes.draw do

  devise_for :teachers

	namespace :admin do
		resources :consultations
		resources :publications
		resources :subjects do
			resources :hours
			resources :exercises_lists
			resources :lectures do
				resources :resources, :controller => "lecture_resources"
			end
		end
		resource :timetable do
			resources :events
			resources :event_types
		end

		match '/contact/update' => 'contact#update', :as => :contact_update
		match '/fb/connect'     => 'fb#connect',     :as => :connect_to_fb
		match '/fb/disconnect'  => 'fb#disconnect',  :as => :disconnect_from_fb

		root :to => 'contact#index'
	end

	resources :teachers, :only => [:index] do
		resource :contact, :only => [:show]
		resources :publications, :only => [:index]
		resources :subjects, :only => [:index, :show] do
			resources :exercises_lists, :only => [:show]
		end
	end

	root :to => 'teachers#index'

end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
  belongs_to :teacher
end

app/controllers/admin/consultations_controller.rb
class Admin::ConsultationsController < Admin::AdminController
  def index
		@consultations = current_teacher.consultations
		@consult = current_teacher.consultations.new
		@consult.start = Time.zone.now
		@consult.end = Time.zone.now + 2.hour
	end

	def create
		@consult = current_teacher.consultations.create(params[:consultation])
		post_on_fb(@consult)

		redirect_to admin_consultations_path
	end

	def edit
		@consult = current_teacher.consultations.find(params[:id])
	end

	def update
		@consult = current_teacher.consultations.find(params[:id])

		if @consult.update_attributes(params[:consultation])
			redirect_to admin_consultations_path
		else
			render :action => "edit"
		end
	end

	def destroy
		@consult = current_teacher.consultations.find(params[:id])
		@consult.destroy()

		redirect_to admin_consultations_path
	end

	private
	def post_on_fb(cons)
		fb = current_teacher.facebook
		unless fb.nil?
			fb.post_to_wal("Dodałem konsultacje w dniu: "+cons.day)
		end
	end
end

app/views/admin/consultations/_consult_form.html.haml
- if consult.errors.any?
  %div.errors
    %ul
      - consult.errors.full_messages.each do |e|
        %li= e

%p
  = f.label :day, "Dzień tygodnia"
  = f.select :day, [["poniedziałek"], ["wtorek"], ["środa"], ["czwartek"], ["piątek"], ["sobota"], ["niedziela"]]
%p
  = f.label :start, "Godziny"
  = f.text_field :start, :size => 4, :value => consult.start.strftime("%H:%M")
  \-
  = f.text_field :end, :size => 4, :value => consult.end.strftime("%H:%M")
%p
  = f.label :comments, "Uwagi"
  = f.text_area :comments, :cols => 60, :rows => 5

app/views/admin/consultations/edit.html.haml
= render :partial => "admin/contact/left_menu"

%h3 Edytuj konsultacje

= form_for [:admin, @consult] do |f|
  = render :partial => "consult_form", :locals => { :f => f, :consult => @consult }
  %p= f.submit "Zmień"

app/views/admin/consultations/index.html.haml
= render :partial => "admin/contact/left_menu"

%h2 Konsultacje

%table.admin_table#konsultacje_table
  %thead
    %tr
      %th#dzien Dzień tygodnia
      %th#godziny Godziny
      %th#uwagi Uwagi
      %th#akcje Działania
  %tbody
    - @consultations.each do |c|
      %tr
        %td= c.day
        %td
          = c.start.strftime("%H:%M")
          \-
          = c.end.strftime("%H:%M")
        %td
          - if c.comments.nil? || c.comments.empty?
            \---
          - else
            = c.comments
        %td
          = link_to "edytuj", edit_admin_consultation_path(c)
          = link_to "usuń", admin_consultation_path(c), :confirm => "Czy na pewno usunąć?", :method => :delete

%h3 Dodaj nowe konsultacje

= form_for [:admin, @consult] do |f|
  = render :partial => "consult_form", :locals => { :f => f, :consult => @consult }
  %p= f.submit "Dodaj"