config/routes.rb
Projekt::Application.routes.draw do

  devise_for :teachers

	namespace :admin do
		resources :consultations
		resources :publications
		resources :subjects do
			resources :hours
			resources :exercises_lists
			resources :lectures do
				resources :resources, :controller => "lecture_resources"
			end
		end
		resource :timetable do
			resources :events
			resources :event_types
		end

		match '/contact/update' => 'contact#update', :as => :contact_update
		match '/fb/connect'     => 'fb#connect',     :as => :connect_to_fb
		match '/fb/disconnect'  => 'fb#disconnect',  :as => :disconnect_from_fb

		root :to => 'contact#index'
	end

	resources :teachers, :only => [:index] do
		resource :contact, :only => [:show]
		resources :publications, :only => [:index]
		resources :subjects, :only => [:index, :show] do
			resources :exercises_lists, :only => [:show]
		end
	end

	root :to => 'teachers#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :timetable
	belongs_to :event_type

	# podaje ile minut trwa dane wydarzenie/zajęcia
	def duration_in_minutes
		return ((self.end - self.start) / (60 * 2)).to_i;
	end

	# podaje ile minut upłynęło od początku dnia do rozpoczęcia wydarzenia
	def minutes_since_beginning
		beginning = Time.utc(start.year, start.month, start.day, 7, 0)

		return ((start - beginning) / (60 * 2)).to_i
	end

	# podaje ile pixeli powinna wynosić wysokość wydarzenia (uwzględnia też linie poziome, które są szerokości 1px)
	def height_pixels
		duration = duration_in_minutes

		if duration > 30
			duration = duration + (duration / 30).to_i
		end

		return duration.to_s + "px"
	end

	# podaje ile pixeli od góry wydarzenie powinno być przesunięte (uwzględnia też linie poziome, które są szerokości 1px)
	def pixels_from_top
		minutes = minutes_since_beginning
		pixels = (minutes + (minutes / 30) -1).to_i

		return pixels.to_s + "px"
	end
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  has_many :events
	belongs_to :event_type_color
	belongs_to :timetable

	def self.default_types
		return self.where(:timetable_id => nil).all
	end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  def new
		load_timetable
		@event = current_teacher.timetable.events.new(:start => Time.zone.now, :end => Time.zone.now + 2.hour)
	end

	def create
		@event = current_teacher.timetable.events.create(params[:event])

		if @event.valid?
			redirect_to admin_timetable_path
		else
			render :action => "new"
		end
	end

	def edit
		load_timetable
		@event = current_teacher.timetable.events.find(params[:id])
	end

	def update
		@event = current_teacher.timetable.events.find(params[:id])

		if @event.update_attributes(params[:event])
			redirect_to admin_timetable_path
		else
			render :action => "edit"
		end
	end

	def destroy
		event = current_teacher.timetable.events.find(params[:id])
		event.destroy

		redirect_to admin_timetable_path
	end

	private
	def load_timetable
		@timetable = current_teacher.timetable
	end
end

app/views/admin/events/_event_form.html.haml
- if event.errors.any?
  %div.errors
    %ul
      - event.errors.full_messages.each do |e|
        %li= e
%p
  = f.label :title, "Nazwa"
  = f.text_field :title, :size => 50
%p
  = f.label :event_type_id, "Typ"
  = f.collection_select :event_type_id, event.timetable.event_types_with_default, :id, :name
%p
  = f.label :week_day, "Dzień tygodnia"
  = f.select :week_day, [["poniedziałek"], ["wtorek"], ["środa"], ["czwartek"], ["piątek"], ["sobota"], ["niedziela"]]
%p
  = f.label :start, "Godziny"
  = f.text_field :start, :size => 4, :value => event.start.strftime("%H:%M")
  \-
  = f.text_field :end, :size => 4, :value => event.end.strftime("%H:%M")
%p
  = f.label :description, "Opis"
  = f.text_area :description, :cols => 60, :rows => 5

app/views/admin/events/edit.html.haml
= render :partial => "/admin/event_types/left_menu"

%h2 Plan zajęć
%h3 Edytuj wydarzenie/zajęcia

= form_for [:admin, @event], :url => admin_timetable_event_path(@event) do |f|
  = render :partial => "event_form", :locals => { :f => f, :event => @event }
  %p= f.submit "Zmień"

app/views/admin/events/new.html.haml
= render :partial => "/admin/event_types/left_menu"

%h2 Plan zajęć
%h3 Dodaj wydarzenie/zajęcia

= form_for [:admin, @event], :url => admin_timetable_events_path do |f|
  = render :partial => "event_form", :locals => { :f => f, :event => @event }
  %p= f.submit "Dodaj"