config/routes.rb
Projekt::Application.routes.draw do

  devise_for :teachers

	namespace :admin do
		resources :consultations
		resources :publications
		resources :subjects do
			resources :hours
			resources :exercises_lists
			resources :lectures do
				resources :resources, :controller => "lecture_resources"
			end
		end
		resource :timetable do
			resources :events
			resources :event_types
		end

		match '/contact/update' => 'contact#update', :as => :contact_update
		match '/fb/connect'     => 'fb#connect',     :as => :connect_to_fb
		match '/fb/disconnect'  => 'fb#disconnect',  :as => :disconnect_from_fb

		root :to => 'contact#index'
	end

	resources :teachers, :only => [:index] do
		resource :contact, :only => [:show]
		resources :publications, :only => [:index]
		resources :subjects, :only => [:index, :show] do
			resources :exercises_lists, :only => [:show]
		end
	end

	root :to => 'teachers#index'

end

app/models/exercises_list.rb
class ExercisesList < ActiveRecord::Base
  belongs_to :subject
	has_one :exercises_lists_file

	validates :nr, :presence => { :message => "Nie podano numeru listy" }
	validates :deadline, :presence => { :message => "Nie podano daty oddania listy lub podano ją w złym formacie" }
	validates :url, :presence => { :message => "Nie podano adresu url listy zadań" }, :if => :upload_present?

	def upload_present?
		exercises_lists_file.nil?
	end
end

app/controllers/admin/exercises_lists_controller.rb
class Admin::ExercisesListsController < Admin::AdminController
  def index
		@subject = get_current_subject(params[:subject_id])
		@exercises_list = @subject.exercises_lists.all
	end

	def new
		@subject = get_current_subject(params[:subject_id])
		@exercises_list = @subject.exercises_lists.new

		list_number = @subject.exercises_lists.maximum(:nr) || 0
		@exercises_list.nr = list_number + 1;
	end

	def create
		@subject = get_current_subject(params[:subject_id])
		@exercises_list = @subject.exercises_lists.create(params[:exercises_list])

		if @exercises_list.valid?
			redirect_to admin_subject_exercises_lists_path(@subject)
		else
			render :action => "new"
		end
	end

	def edit
		@subject = get_current_subject(params[:subject_id])
		@exercises_list = @subject.exercises_lists.find(params[:id])
	end

	def update
		@subject = get_current_subject(params[:subject_id])
		@exercises_list = @subject.exercises_lists.find(params[:id])

		if @exercises_list.update_attributes(params[:exercises_list])
			redirect_to admin_subject_exercises_lists_path(@subject)
		else
			render :action => "edit"
		end
	end

	def destroy
		@subject = get_current_subject(params[:subject_id])
		@exercises_list = @subject.exercises_lists.find(params[:id])
		@exercises_list.destroy

		redirect_to admin_subject_exercises_lists_path(@subject)
	end
end

app/views/admin/exercises_lists/_exer_form.html.haml
- if exercises_list.errors.any?
  %div.errors
    %ul
      - exercises_list.errors.full_messages.each do |e|
        %li= e
%p
  = f.label :nr, "Numer"
  = f.text_field :nr, :size => 4
%p
  = f.label :deadline, "Termin oddania"
  = f.text_field :deadline, :size => 20
%p
  = f.label :url, "Link do listy"
  = f.text_field :url, :size => 50
%p
  = f.label :comment, "Dodatkowe uwagi"
  = f.text_field :comment, :size => 50

app/views/admin/exercises_lists/edit.html.haml
- render :partial => "admin/subjects/subject_inner_menu"

%h2
  Edytuj listę nr
  =@exercises_list.nr

= form_for [:admin, @exercises_list.subject, @exercises_list], :html => { :multipart => true } do |f|
  = render :partial => "exer_form", :locals => { :f => f, :exercises_list => @exercises_list }
  %p= f.submit "Edytuj"

app/views/admin/exercises_lists/index.html.haml
- render :partial => "admin/subjects/subject_inner_menu"

%h2 Listy zadań

%p= link_to "Dodaj listę zadań", new_admin_subject_exercises_list_path(@subject)

%table.admin_table#exercises_lists_table
  %thead
    %tr
      %th Nr
      %th Plik/link
      %th Termin oddania
      %th Uwagi
      %th Data dodania
      %th Działania
  %tbody
    - @subject.exercises_lists.each do |ex|
      %tr
        %td= ex.nr
        %td
          - if ex.url.nil? || ex.url.empty?
            Nazwa pliku z listą
          - else
            = link_to truncate(ex.url, :length => 40), ex.url
        %td= ex.deadline.strftime("%d-%m-%Y")
        %td
          - if ex.comment.nil? || ex.comment.empty?
            \---
          - else
            = ex.comment
        %td= ex.created_at.strftime("%d-%m-%Y %H:%M")
        %td
          = link_to "edytuj", edit_admin_subject_exercises_list_path(ex.subject, ex)
          = link_to "usuń", admin_subject_exercises_list_path(ex.subject, ex), :confirm => "Czy na pewno usunąć?", :method => :delete

app/views/admin/exercises_lists/new.html.haml
- render :partial => "admin/subjects/subject_inner_menu"

%h2 Dodaj listę zadań

= form_for [:admin, @exercises_list.subject, @exercises_list], :html => { :multipart => true } do |f|
  = render :partial => "exer_form", :locals => { :f => f, :exercises_list => @exercises_list }
  %p= f.submit "Dodaj"