config/routes.rb
Projekt::Application.routes.draw do

  devise_for :teachers

	namespace :admin do
		resources :consultations
		resources :publications
		resources :subjects do
			resources :hours
			resources :exercises_lists
			resources :lectures do
				resources :resources, :controller => "lecture_resources"
			end
		end
		resource :timetable do
			resources :events
			resources :event_types
		end

		match '/contact/update' => 'contact#update', :as => :contact_update
		match '/fb/connect'     => 'fb#connect',     :as => :connect_to_fb
		match '/fb/disconnect'  => 'fb#disconnect',  :as => :disconnect_from_fb

		root :to => 'contact#index'
	end

	resources :teachers, :only => [:index] do
		resource :contact, :only => [:show]
		resources :publications, :only => [:index]
		resources :subjects, :only => [:index, :show] do
			resources :exercises_lists, :only => [:show]
		end
	end

	root :to => 'teachers#index'

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :teacher
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < Admin::AdminController
  def index
		@publications = current_teacher.publications.all
		@pub = current_teacher.publications.new
	end

	def create
		@pub = current_teacher.publications.create(params[:publication])

		redirect_to admin_publications_path
	end

	def edit
		@pub = current_teacher.publications.find(params[:id])
	end

	def update
		@pub = current_teacher.publications.find(params[:id])

		if @pub.update_attributes(params[:publication])
			redirect_to admin_publications_path
		else
			render :action => "edit"
		end
	end

	def destroy
		pub = current_teacher.publications.find(params[:id])
		pub.destroy()

		redirect_to admin_publications_path
	end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  def index
		teacher = Teacher.find(params[:teacher_id])
		@publications = teacher.publications
	end
end

app/views/admin/publications/_local_menu.html.haml
- content_for(:local_menu) do
  %ul
    %li= link_to_unless_current "Wszystkie", admin_publications_path

app/views/admin/publications/_publications_form.html.haml
%p
  = f.label :co_authors, "Współautorzy"
  = f.text_field :co_authors, :size => 60
%p
  = f.label :title, "Tytuł"
  = f.text_field :title, :size => 80
%p
  = f.label :year, "Rok"
  = f.select :year, [[2000], [2001], [2002], [2003], [2004], [2006], [2007], [2008], [2009], [2010], [2011]]
%p
  = f.label :link, "Link"
  = f.text_field :link, :size => 60

app/views/admin/publications/edit.html.haml
- render :partial => "local_menu"

%h2 Edytuj publikację

= form_for [:admin, @pub] do |f|
  - if @pub.errors.any?
    %div.errors
      %ul
        - @pub.errors.full_messages.each do |e|
          %li= e
  = render :partial => "publications_form", :locals => { :f => f }
  %p= f.submit "Edytuj"

app/views/admin/publications/index.html.haml
- render :partial => "local_menu"

%h2 Publikacje

%table.admin_table#publikacje_table
  %thead
    %tr
      %th Współautorzy
      %th Tytuł
      %th Rok
      %th Odnośnik
      %th Akcje
  %tbody
    - @publications.each do |p|
      %tr
        %td= p.co_authors
        %td= p.title
        %td= p.year
        %td= link_to p.link, p.link
        %td
          = link_to "edytuj", edit_admin_publication_path(p)
          = link_to "usuń", admin_publication_path(p), :confirm => "Czy na pewno usunąć?", :method => :delete

%h3 Dodaj nową publikację

= form_for [:admin, @pub] do |f|
  = render :partial => "publications_form", :locals => { :f => f }
  %p= f.submit "Dodaj"